version: "3.8"
services:
  api:
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env.prd
    ports:
      - 8080:8080
    command: npm run start
