version: "3.8"
services:
  api:
    container_name: trilha-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    working_dir: '/usr/app'
    environment:
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '4000:4000'
    command: >
      sh -c "npx prisma generate &&
      npx prisma migrate deploy &&
      npm run build && npm run start"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules