@BASE_URL = http://localhost:3333/api/task

### Get all tasks
GET {{BASE_URL}}

### Create task
POST {{BASE_URL}}
Content-Type: application/json

{
  "title": "Task Title",
  "description": "Task Description"
}

### Get task by ID
GET {{BASE_URL}}/06310188-9150-4034-9ebc-aa6f8c69b7ba


### Update task
POST {{BASE_URL}}/06310188-9150-4034-9ebc-aa6f8c69b7ba
Content-Type: application/json

{
  "title": "Task Title1"
}

### Delete task
DELETE {{BASE_URL}}/15d1a80e-d092-46ad-929c-fa7fade0500f