@BASE_URL = http://localhost:3333/api/task

### Get all tasks
GET {{BASE_URL}}?take=2

### Create task
POST {{BASE_URL}}
Content-Type: application/json

{
  "title": "Task Title2",
  "description": "Task Description"
}

### Get task by ID
GET {{BASE_URL}}/06310188-9150-4034-9ebc-aa6f8c69b7ba


### Update task
POST {{BASE_URL}}/06310188-9150-4034-9ebc-aa6f8c69b7ba
Content-Type: application/json

{
  "title": "Task Title1"
}