@BASE_URL = http://localhost:3333/api/task

### Get all tasks
GET {{BASE_URL}}?take=2

### Create tasks
POST {{BASE_URL}}
Content-Type: application/json

{
  "title": "Task Title2",
  "description": "Task Description"
}

### Get task by ID
GET {{BASE_URL}}/:id